# Generated by Django 5.0.6 on 2024-05-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_usernmapflagpermission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
